### ISSUE TITLE
Research Display enviromental info

### ISSUE THREAD

**Issue by NathanRoseCE** [NathanRoseCE/Senior_Design_ECOCAR_UI#5]

**Comment by Tejatiriveedhi** [comment]
1.    Infrastructure story: As a UI team member, I want to do a research on the technologies to use for the car to be able to display environmental info such as the speed and other external conditions like outside temperature, on the car windowshield. 
2.    Demo Criteria: Research report comparing displayed data on the window shield with the one in the car speedometer. 
3.    Category: Must have. 
4.    Priority: first class.
