### ISSUE TITLE
Research Ros

### ISSUE THREAD

**Issue by NathanRoseCE** [NathanRoseCE/Senior_Design_ECOCAR_UI#7]
1.    Infrastructure story: As a UI team member, I want to do a research on the operating system ROS to implement it on the car in order to have the car use computer based operating systems 
2.    Demo Criteria: Research report comparing different potential choices and the usage of communcating by sending and receiving messages
3.    Category: Must have. 
4.    Priority: first class.

**Comment by fadinidERAU** [comment]
**Infrastructure Story** As a UI team member, I want to do research on how the ROS system can be interfaced with using Python to allow a flexible development strategy utilizing Python
**Demo Criteria** Research Rospy documentation on how to use the API to receive and send messages with ROS
**Category** Must have
**Priority** First Class
